development:
  adapter: postgresql
  encoding: unicode
  database: silver_fit_dev
  pool: 5
  host: localhost
  username: Jason

test:
  adapter: postgresql
  encoding: unicode
  database: silver_fit_test
  pool: 5
  host: localhost
  username: Jason

production:
  adapter: postgresql
  encoding: unicode
  database: silver_fit_production
  pool: 5
  username: Jason
